/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package schooltech.ictsupport;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import schooltech.ictsupport.User.LoginClass;

/**
 *
 * @author YLADx
 */
public class Login_Interface extends javax.swing.JFrame {

    /**
     * Creates new form Login_Interface
     */
    public Login_Interface() {
        initComponents();
    //make background image fit to jlabel name BackgoundImagpic
    
         setLocationRelativeTo(null);
        LoginInput.setBackground(new Color (255,255,255,150));
        ProjectName.setText("<html><div style='text-align: center;'>  SchoolTech   ICT Support </div></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        LoginText = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        ProjectName = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        LoginInput = new javax.swing.JPanel();
        EmailLabel = new javax.swing.JLabel();
        EmailInput = new javax.swing.JFormattedTextField();
        Passwordlabel = new javax.swing.JLabel();
        PasswordInput = new javax.swing.JPasswordField();
        Register = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        BackGroundPic = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SchoolTech");
        setMinimumSize(new java.awt.Dimension(720, 450));
        setPreferredSize(new java.awt.Dimension(720, 450));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        LoginText.setBackground(new java.awt.Color(255, 254, 239));
        LoginText.setFont(new java.awt.Font("Nineteen Ninety Seven", 1, 20)); // NOI18N
        LoginText.setForeground(new java.awt.Color(33, 33, 33));
        LoginText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginText.setText("LOG IN");
        LoginText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 33, 33), 2));
        LoginText.setOpaque(true);
        jPanel2.add(LoginText);
        LoginText.setBounds(420, 70, 160, 40);

        Left.setBackground(new java.awt.Color(255, 255, 204));
        Left.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Left.setForeground(new java.awt.Color(255, 255, 204));

        ProjectName.setFont(new java.awt.Font("Nineteen Ninety Seven", 1, 14)); // NOI18N
        ProjectName.setForeground(new java.awt.Color(33, 33, 33));
        ProjectName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProjectName.setText("SchoolTech ");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-technical-support-100.png"))); // NOI18N

        Back.setBackground(new java.awt.Color(255, 254, 239));
        Back.setFont(new java.awt.Font("Nineteen Ninety Seven", 0, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(33, 33, 33));
        Back.setText("<<");
        Back.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Back.setContentAreaFilled(false);
        Back.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Back.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftLayout = new javax.swing.GroupLayout(Left);
        Left.setLayout(LeftLayout);
        LeftLayout.setHorizontalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                .addGroup(LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LeftLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(ProjectName, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, LeftLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Back)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Logo)
                .addGap(91, 91, 91))
        );
        LeftLayout.setVerticalGroup(
            LeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Back)
                .addGap(27, 27, 27)
                .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProjectName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(224, 224, 224))
        );

        jPanel2.add(Left);
        Left.setBounds(0, 0, 290, 420);

        LoginInput.setBackground(new java.awt.Color(204, 204, 204));
        LoginInput.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 33, 33), 2));
        LoginInput.setForeground(new java.awt.Color(51, 51, 51));
        LoginInput.setLayout(null);

        EmailLabel.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(102, 102, 102));
        EmailLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-email-16.png"))); // NOI18N
        EmailLabel.setText("Email:");
        LoginInput.add(EmailLabel);
        EmailLabel.setBounds(20, 30, 70, 16);

        EmailInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailInputActionPerformed(evt);
            }
        });
        LoginInput.add(EmailInput);
        EmailInput.setBounds(20, 50, 264, 22);

        Passwordlabel.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        Passwordlabel.setForeground(new java.awt.Color(102, 102, 102));
        Passwordlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-password-16 (1).png"))); // NOI18N
        Passwordlabel.setText(" Password:");
        LoginInput.add(Passwordlabel);
        Passwordlabel.setBounds(20, 80, 100, 20);

        PasswordInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordInputActionPerformed(evt);
            }
        });
        LoginInput.add(PasswordInput);
        PasswordInput.setBounds(20, 100, 264, 22);

        jPanel2.add(LoginInput);
        LoginInput.setBounds(350, 90, 300, 160);

        Register.setBackground(new java.awt.Color(204, 255, 255));
        Register.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        Register.setForeground(new java.awt.Color(102, 0, 0));
        Register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-sign-up-24.png"))); // NOI18N
        Register.setText("Have You Not Register Your Accpunt Click this to Register:");
        Register.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Register.setContentAreaFilled(false);
        Register.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        jPanel2.add(Register);
        Register.setBounds(330, 380, 360, 30);

        LoginButton.setBackground(new java.awt.Color(165, 250, 165));
        LoginButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(153, 153, 153));
        LoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-login-24.png"))); // NOI18N
        LoginButton.setText("LOG IN");
        LoginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LoginButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(LoginButton);
        LoginButton.setBounds(350, 260, 300, 30);

        BackGroundPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/BackGround/8351249.gif"))); // NOI18N
        BackGroundPic.setDoubleBuffered(true);
        jPanel2.add(BackGroundPic);
        BackGroundPic.setBounds(-670, 0, 1550, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        try {
            new MainInterface().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Login_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void PasswordInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordInputActionPerformed
       char[] passwordChars = PasswordInput.getPassword();
       
       
        LoginButtonActionPerformed(evt);
    }//GEN-LAST:event_PasswordInputActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        try {
            new RegisterAccount().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Login_Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
            this.dispose();
    }//GEN-LAST:event_RegisterActionPerformed

    private void EmailInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailInputActionPerformed
         String userEmail = EmailInput.getText();
        
        //if you press enter it wll jump to password input box
        PasswordInput.requestFocusInWindow();
    }//GEN-LAST:event_EmailInputActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        LoginClass Loginverification = new LoginClass(EmailInput, PasswordInput);
         if(!Loginverification.performLogin()){
             return;
             
         };
        
      String LoginUser = Loginverification.getloginemail();

    new UserEmailMainInterface(LoginUser).setVisible(true);
    this.dispose();
       
    }//GEN-LAST:event_LoginButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JLabel BackGroundPic;
    private javax.swing.JFormattedTextField EmailInput;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPanel Left;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPanel LoginInput;
    private javax.swing.JLabel LoginText;
    private javax.swing.JLabel Logo;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JLabel Passwordlabel;
    private javax.swing.JLabel ProjectName;
    private javax.swing.JButton Register;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
